# Generated by Django 4.1.7 on 2023-02-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
